/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views.admin.StudioManagement;
import java.util.logging.Logger;
import controllers.StudioController;

/**
 *
 * @author rhy1caa
 */
public class JDialog_Create extends javax.swing.JDialog {
    
    private static final Logger logger = Logger.getLogger(JDialog_Create.class.getName());
    
    private final StudioController studioController;
    
    /**
     * Creates new form JDialog_Create
     * @param parent
     * @param modal
     */
    public JDialog_Create(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.studioController = new StudioController();
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Tambah Studio Baru");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Field_NamaStudio = new javax.swing.JTextField();
        Field_TipeStudio = new javax.swing.JComboBox<>();
        Btn_BatalSimpanStudio = new javax.swing.JButton();
        Btn_SimpanStudio = new javax.swing.JButton();
        Spinner_BarisStudio = new javax.swing.JSpinner();
        Spinner_KolomStudio = new javax.swing.JSpinner();
        Btn_XatauBatal = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setPreferredSize(new java.awt.Dimension(680, 500));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tambah Studio");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tambahkan Data Studio dengan Mengisi Field di Bawah");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Studio");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipe Studio");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jumlah Baris");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jumlah Kolom");

        Field_NamaStudio.addActionListener(this::Field_NamaStudioActionPerformed);

        Field_TipeStudio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deluxe", "Ultra XD", "IMAX", "Sphere" }));
        Field_TipeStudio.addActionListener(this::Field_TipeStudioActionPerformed);

        Btn_BatalSimpanStudio.setText("Batal");
        Btn_BatalSimpanStudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_BatalSimpanStudioMouseClicked(evt);
            }
        });
        Btn_BatalSimpanStudio.addActionListener(this::Btn_BatalSimpanStudioActionPerformed);

        Btn_SimpanStudio.setText("Simpan");
        Btn_SimpanStudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_SimpanStudioMouseClicked(evt);
            }
        });
        Btn_SimpanStudio.addActionListener(this::Btn_SimpanStudioActionPerformed);

        Btn_XatauBatal.setBackground(new java.awt.Color(195, 156, 0));
        Btn_XatauBatal.setText("X");
        Btn_XatauBatal.addActionListener(this::Btn_XatauBatalActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_XatauBatal)
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Btn_BatalSimpanStudio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Btn_SimpanStudio))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(34, 34, 34))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(29, 29, 29)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Spinner_KolomStudio)
                                    .addComponent(Spinner_BarisStudio)
                                    .addComponent(Field_TipeStudio, 0, 340, Short.MAX_VALUE)
                                    .addComponent(Field_NamaStudio)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel2)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Btn_XatauBatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Field_TipeStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(Field_NamaStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Spinner_BarisStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Spinner_KolomStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_SimpanStudio)
                    .addComponent(Btn_BatalSimpanStudio))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Field_NamaStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_NamaStudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_NamaStudioActionPerformed

    private void Field_TipeStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_TipeStudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_TipeStudioActionPerformed

    private void Btn_BatalSimpanStudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_BatalSimpanStudioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_BatalSimpanStudioMouseClicked

    private void Btn_BatalSimpanStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BatalSimpanStudioActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Btn_BatalSimpanStudioActionPerformed

    private void Btn_SimpanStudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_SimpanStudioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SimpanStudioMouseClicked

    private void Btn_SimpanStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SimpanStudioActionPerformed
        // TODO add your handling code here:
        String nama = Field_NamaStudio.getText().trim();
        String tipe = Field_TipeStudio.getSelectedItem().toString();
        int baris = (int) Spinner_BarisStudio.getValue();
        int kolom = (int) Spinner_KolomStudio.getValue();

        if (nama.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Nama studio wajib diisi!",
                "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            Field_NamaStudio.requestFocus();
            return;
        }
        
        if (baris <= 0 || kolom <= 0) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Jumlah baris dan kolom harus lebih dari 0!",
                "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        } 
        
         String namaLengkap = nama + " (" + tipe + ")";
         
         boolean sukses = studioController.tambahStudio(namaLengkap, baris, kolom);

        if (sukses) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Studio \"" + namaLengkap + "\" berhasil ditambahkan!\nKapasitas: " + (baris * kolom) + " kursi.",
                "Sukses",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
            this.dispose(); // Tutup dialog setelah berhasil
        } else {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Gagal menyimpan data ke database.\nPastikan koneksi database aktif.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_Btn_SimpanStudioActionPerformed

    private void Btn_XatauBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_XatauBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Btn_XatauBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JDialog_Create dialog = new JDialog_Create(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_BatalSimpanStudio;
    private javax.swing.JButton Btn_SimpanStudio;
    private javax.swing.JButton Btn_XatauBatal;
    private javax.swing.JTextField Field_NamaStudio;
    private javax.swing.JComboBox<String> Field_TipeStudio;
    private javax.swing.JSpinner Spinner_BarisStudio;
    private javax.swing.JSpinner Spinner_KolomStudio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
