/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views.admin.StudioManagement;
import controllers.StudioController;
import java.util.logging.Logger;
/**
 *
 * @author rhy1caa
 */
public class JDialog_UpdateStudio extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialog_UpdateStudio.class.getName());
    private final StudioController studioController;
    private int idStudioYangDiedit = -1;

    /**
     * Creates new form JDialog_UpdateStudio
     */
    public JDialog_UpdateStudio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.studioController = new StudioController();
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Edit Data Studio");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Field_NamaStudioEdut = new javax.swing.JTextField();
        Field_TipeStudioEdut = new javax.swing.JComboBox<>();
        Btn_BatalSimpanStudioEdit = new javax.swing.JButton();
        Btn_SimpanStudioEdit = new javax.swing.JButton();
        Spinner_BarisStudioEdit = new javax.swing.JSpinner();
        Spinner_ViewsStudioEdit = new javax.swing.JSpinner();
        Btn_XatauBatal4 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        Field_IDStudioEdit = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(16, 25, 53));
        setModal(true);

        jPanel6.setBackground(new java.awt.Color(0, 51, 102));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Edit Studio");

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Tambahkan Data Studio dengan Mengisi Field di Bawah");

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Nama Studio");

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Tipe Studio");

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Jumlah Baris");

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Jumlah Kolom");

        Field_NamaStudioEdut.addActionListener(this::Field_NamaStudioEdutActionPerformed);

        Field_TipeStudioEdut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deluxe", "Ultra XD", "IMAX", "Sphere" }));
        Field_TipeStudioEdut.addActionListener(this::Field_TipeStudioEdutActionPerformed);

        Btn_BatalSimpanStudioEdit.setText("Batal");
        Btn_BatalSimpanStudioEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_BatalSimpanStudioEditMouseClicked(evt);
            }
        });
        Btn_BatalSimpanStudioEdit.addActionListener(this::Btn_BatalSimpanStudioEditActionPerformed);

        Btn_SimpanStudioEdit.setText("Simpan");
        Btn_SimpanStudioEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_SimpanStudioEditMouseClicked(evt);
            }
        });
        Btn_SimpanStudioEdit.addActionListener(this::Btn_SimpanStudioEditActionPerformed);

        Btn_XatauBatal4.setBackground(new java.awt.Color(226, 209, 110));
        Btn_XatauBatal4.setText("X");

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("ID");

        Field_IDStudioEdit.addActionListener(this::Field_IDStudioEditActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(188, 188, 188)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Field_NamaStudioEdut)
                    .addComponent(Field_TipeStudioEdut, 0, 329, Short.MAX_VALUE)
                    .addComponent(Spinner_BarisStudioEdit)
                    .addComponent(Spinner_ViewsStudioEdit)
                    .addComponent(Field_IDStudioEdit))
                .addGap(76, 76, 76))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(Btn_BatalSimpanStudioEdit)
                .addGap(36, 36, 36)
                .addComponent(Btn_SimpanStudioEdit)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(Btn_XatauBatal4)
                        .addGap(24, 24, 24))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel25)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Btn_XatauBatal4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(Field_IDStudioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Field_TipeStudioEdut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(Field_NamaStudioEdut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Spinner_BarisStudioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Spinner_ViewsStudioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_SimpanStudioEdit)
                    .addComponent(Btn_BatalSimpanStudioEdit))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void setDataStudio(int id, String namaLengkap, int baris, int kolom) {
        this.idStudioYangDiedit = id;
        Field_ID.setText(String.valueOf(id));
        Spinner_Baris.setValue(baris);
        Spinner_Kolom.setValue(kolom);

        // Pisahkan nama dan tipe dari format "Studio 1 (IMAX)"
        if (namaLengkap != null && namaLengkap.contains(" (") && namaLengkap.endsWith(")")) {
            int idxBuka  = namaLengkap.lastIndexOf(" (");
            String nama  = namaLengkap.substring(0, idxBuka).trim();
            String tipe  = namaLengkap.substring(idxBuka + 2, namaLengkap.length() - 1).trim();
            Field_NamaStudio.setText(nama);
            Field_TipeStudio.setSelectedItem(tipe);
        } else {
            // Fallback jika format tidak sesuai
            Field_NamaStudio.setText(namaLengkap);
        }
    }
     
    private void Field_NamaStudioEdutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_NamaStudioEdutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_NamaStudioEdutActionPerformed

    private void Field_TipeStudioEdutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_TipeStudioEdutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_TipeStudioEdutActionPerformed

    private void Btn_BatalSimpanStudioEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_BatalSimpanStudioEditMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_BatalSimpanStudioEditMouseClicked

    private void Btn_BatalSimpanStudioEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BatalSimpanStudioEditActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Btn_BatalSimpanStudioEditActionPerformed

    private void Btn_SimpanStudioEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_SimpanStudioEditMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SimpanStudioEditMouseClicked

    private void Btn_SimpanStudioEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SimpanStudioEditActionPerformed
        // TODO add your handling code here:
        
         if (idStudioYangDiedit == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Terjadi kesalahan: ID studio tidak ditemukan.",
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
         return;
        }
         
        String nama  = Field_NamaStudio.getText().trim();
        String tipe  = Field_TipeStudio.getSelectedItem().toString();
        int    baris = (int) Spinner_Baris.getValue();
        int    kolom = (int) Spinner_Kolom.getValue();

        if (nama.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Nama studio wajib diisi!",
                "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            Field_NamaStudio.requestFocus();
            return;
        }

        if (baris <= 0 || kolom <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Jumlah baris dan kolom harus lebih dari 0!",
                "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String namaLengkap = nama + " (" + tipe + ")";

        boolean sukses = studioController.updateStudio(idStudioYangDiedit, namaLengkap, baris, kolom);

        if (sukses) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Data studio berhasil diperbarui!",
                "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Gagal memperbarui data. Periksa koneksi database.",
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_Btn_SimpanStudioEditActionPerformed

    private void Field_IDStudioEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_IDStudioEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_IDStudioEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialog_UpdateStudio dialog = new JDialog_UpdateStudio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_BatalSimpanStudio;
    private javax.swing.JButton Btn_BatalSimpanStudio1;
    private javax.swing.JButton Btn_BatalSimpanStudio2;
    private javax.swing.JButton Btn_BatalSimpanStudioEdit;
    private javax.swing.JButton Btn_SimpanStudio;
    private javax.swing.JButton Btn_SimpanStudio1;
    private javax.swing.JButton Btn_SimpanStudio2;
    private javax.swing.JButton Btn_SimpanStudioEdit;
    private javax.swing.JButton Btn_XatauBatal;
    private javax.swing.JButton Btn_XatauBatal1;
    private javax.swing.JButton Btn_XatauBatal2;
    private javax.swing.JButton Btn_XatauBatal4;
    private javax.swing.JTextField Field_IDStudioEdit;
    private javax.swing.JTextField Field_NamaStudio;
    private javax.swing.JTextField Field_NamaStudio1;
    private javax.swing.JTextField Field_NamaStudio2;
    private javax.swing.JTextField Field_NamaStudioEdut;
    private javax.swing.JComboBox<String> Field_TipeStudio;
    private javax.swing.JComboBox<String> Field_TipeStudio1;
    private javax.swing.JComboBox<String> Field_TipeStudio2;
    private javax.swing.JComboBox<String> Field_TipeStudioEdut;
    private javax.swing.JSpinner Spinner_BarisStudioEdit;
    private javax.swing.JSpinner Spinner_ViewsStudioEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    // End of variables declaration//GEN-END:variables
}
