/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.admin.StudioManagement;

import controllers.StudioController;
import java.util.logging.Logger;

/**
 *
 * @author rhy1caa
 */
public class StudioManagementFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudioManagementFrame.class.getName());
    private final StudioController studioController;

    /**
     * Creates new form StudioManagementFrame
     */
    public StudioManagementFrame() {
       this.studioController = new StudioController();
       initComponents();
       setLocationRelativeTo(null);
       setTitle("Bioskopin - Kelola Studio");
       loadData(); 
    }
    
     private void loadData() {
        jTable_Studio.setModel(studioController.getTableModel());

        // Atur lebar kolom agar lebih rapi
        if (jTable_Studio.getColumnModel().getColumnCount() > 0) {
            jTable_Studio.getColumnModel().getColumn(0).setPreferredWidth(60);   // ID
            jTable_Studio.getColumnModel().getColumn(1).setPreferredWidth(220);  // Nama
            jTable_Studio.getColumnModel().getColumn(2).setPreferredWidth(80);   // Baris
            jTable_Studio.getColumnModel().getColumn(3).setPreferredWidth(80);   // Kolom
            jTable_Studio.getColumnModel().getColumn(4).setPreferredWidth(80);   // Kapasitas
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_HapusStudio = new javax.swing.JButton();
        JPanel_SideBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ManageStudio = new javax.swing.JTable();
        Btn_TambahStudio2 = new javax.swing.JButton();
        Btn_EditStudio3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btn_HapusStudio.setBackground(new java.awt.Color(226, 209, 110));
        Btn_HapusStudio.setForeground(new java.awt.Color(255, 255, 255));
        Btn_HapusStudio.setText("Hapus Data");
        Btn_HapusStudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_HapusStudioMouseClicked(evt);
            }
        });
        Btn_HapusStudio.addActionListener(this::Btn_HapusStudioActionPerformed);

        JPanel_SideBar.setBackground(new java.awt.Color(16, 25, 53));

        javax.swing.GroupLayout JPanel_SideBarLayout = new javax.swing.GroupLayout(JPanel_SideBar);
        JPanel_SideBar.setLayout(JPanel_SideBarLayout);
        JPanel_SideBarLayout.setHorizontalGroup(
            JPanel_SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        JPanel_SideBarLayout.setVerticalGroup(
            JPanel_SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Kelola Studio");

        jLabel2.setText("Kelola studio yang diinginkan ");

        jTable_ManageStudio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Studio", "Baris", "Kolom", "Kapasitas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_ManageStudio.setName(""); // NOI18N
        jScrollPane1.setViewportView(jTable_ManageStudio);

        Btn_TambahStudio2.setBackground(new java.awt.Color(226, 209, 110));
        Btn_TambahStudio2.setForeground(new java.awt.Color(255, 255, 255));
        Btn_TambahStudio2.setText("+ Tambah Studio");
        Btn_TambahStudio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_TambahStudio2MouseClicked(evt);
            }
        });
        Btn_TambahStudio2.addActionListener(this::Btn_TambahStudio2ActionPerformed);

        Btn_EditStudio3.setBackground(new java.awt.Color(226, 209, 110));
        Btn_EditStudio3.setForeground(new java.awt.Color(255, 255, 255));
        Btn_EditStudio3.setText("Edit Data");
        Btn_EditStudio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_EditStudio3MouseClicked(evt);
            }
        });
        Btn_EditStudio3.addActionListener(this::Btn_EditStudio3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanel_SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_TambahStudio2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_HapusStudio)
                                .addGap(17, 17, 17)
                                .addComponent(Btn_EditStudio3)))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_EditStudio3)
                    .addComponent(Btn_HapusStudio))
                .addGap(18, 18, 18)
                .addComponent(Btn_TambahStudio2)
                .addGap(41, 41, 41))
            .addComponent(JPanel_SideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_HapusStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HapusStudioActionPerformed
        // TODO add your handling code here:
        int barisTerpilih = jTable_Studio.getSelectedRow();

        if (barisTerpilih == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Pilih studio yang ingin dihapus terlebih dahulu.",
                "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int    id   = (int)    jTable_Studio.getValueAt(barisTerpilih, 0);
        String nama = (String) jTable_Studio.getValueAt(barisTerpilih, 1);

        // Minta konfirmasi sebelum menghapus
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus studio \"" + nama + "\"?\nTindakan ini tidak dapat dibatalkan.",
            "Konfirmasi Hapus",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE
        );

        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            boolean sukses = studioController.hapusStudio(id);
            if (sukses) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Studio \"" + nama + "\" berhasil dihapus.",
                    "Sukses",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
                loadData(); // Refresh tabel

                // Jika tabel sudah kosong, kembali ke frame kosong
                if (studioController.isDataKosong()) {
                    BlmAdaStudioManagementFrame frameKosong = new BlmAdaStudioManagementFrame();
                    frameKosong.setVisible(true);
                    this.dispose();
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Gagal menghapus studio. Periksa koneksi database.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_Btn_HapusStudioActionPerformed

    private void Btn_TambahStudio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TambahStudio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_TambahStudio2ActionPerformed

    private void Btn_EditStudio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EditStudio3ActionPerformed
        // TODO add your handling code here:
        int barisTerpilih = jTable_Studio.getSelectedRow();

        if (barisTerpilih == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Pilih studio yang ingin diedit terlebih dahulu.",
                "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Ambil data dari baris terpilih di tabel
        int    id   = (int)    jTable_Studio.getValueAt(barisTerpilih, 0);
        String nama = (String) jTable_Studio.getValueAt(barisTerpilih, 1);
        int    baris = (int)   jTable_Studio.getValueAt(barisTerpilih, 2);
        int    kolom = (int)   jTable_Studio.getValueAt(barisTerpilih, 3);

        // Buka dialog edit dan isi dengan data studio yang dipilih
        JDialog_EditStudio dialog = new JDialog_EditStudio(null, true);
        dialog.setDataStudio(id, nama, baris, kolom);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        loadData(); 
    }//GEN-LAST:event_Btn_EditStudio3ActionPerformed

    private void Btn_HapusStudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_HapusStudioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_HapusStudioMouseClicked

    private void Btn_EditStudio3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_EditStudio3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_EditStudio3MouseClicked

    private void Btn_TambahStudio2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_TambahStudio2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_TambahStudio2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudioManagementFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_EditStudio3;
    private javax.swing.JButton Btn_HapusStudio;
    private javax.swing.JButton Btn_TambahStudio2;
    private javax.swing.JPanel JPanel_SideBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_ManageStudio;
    // End of variables declaration//GEN-END:variables
}
