/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views.admin.FilmManagement;

import controllers.FilmController;
import javax.swing.JOptionPane;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import utils.ColorPalette;

/**
 *
 * @author Rafli Ahmad Fauzi
 */
public class DialogTambahFilm extends javax.swing.JDialog {

    private final FilmController controller;
    /**
     * Creates new form DialogTambahFilm
     */
    public DialogTambahFilm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.controller = new FilmController();
        this.setLocationRelativeTo(parent);
        
        jPanel2.setBackground(ColorPalette.SIDEBAR); 

        jButtonSimpan.setBackground(ColorPalette.PRIMARY);
        jButtonSimpan.setForeground(ColorPalette.WHITE);

        jButtonBatal.setBackground(ColorPalette.BORDER);
        jButtonBatal.setForeground(ColorPalette.SIDEBAR);

        jButtonBrowsePath.setBackground(ColorPalette.SIDEBAR);
        jButtonBrowsePath.setForeground(ColorPalette.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelJudulTambah = new javax.swing.JLabel();
        jLabelSubJudulTambah = new javax.swing.JLabel();
        jLabelJudul = new javax.swing.JLabel();
        jTextFieldJudul = new javax.swing.JTextField();
        jLabelGenre = new javax.swing.JLabel();
        jLabelDurasi = new javax.swing.JLabel();
        jLabelSinopsis = new javax.swing.JLabel();
        jLabelPosterPath = new javax.swing.JLabel();
        jTextFieldPosterPath = new javax.swing.JTextField();
        jComboBoxGenre = new javax.swing.JComboBox<>();
        jSpinnerDurasi = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSinopsis = new javax.swing.JTextArea();
        jButtonBrowsePath = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jButtonSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah Data Film");

        jPanel2.setBackground(new java.awt.Color(16, 25, 53));

        jLabelJudulTambah.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelJudulTambah.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJudulTambah.setText("Tambah Film");

        jLabelSubJudulTambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSubJudulTambah.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubJudulTambah.setText("Tambahkan Data Film dengan Mengisi Field Dibawah");

        jLabelJudul.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJudul.setText("Judul :");

        jLabelGenre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenre.setText("Genre :");

        jLabelDurasi.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDurasi.setText("Durasi (Menit) :");

        jLabelSinopsis.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSinopsis.setText("Sinopsis :");

        jLabelPosterPath.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPosterPath.setText("Poster Path :");

        jTextFieldPosterPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPosterPathActionPerformed(evt);
            }
        });

        jComboBoxGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Action", "Drama", "Horror", "Komedi", "Thriller", "Science Fiction", "Romantis" }));
        jComboBoxGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGenreActionPerformed(evt);
            }
        });

        jSpinnerDurasi.setModel(new javax.swing.SpinnerNumberModel());

        jTextAreaSinopsis.setColumns(20);
        jTextAreaSinopsis.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSinopsis);

        jButtonBrowsePath.setText("Browse");
        jButtonBrowsePath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBrowsePathMouseClicked(evt);
            }
        });
        jButtonBrowsePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowsePathActionPerformed(evt);
            }
        });

        jButtonBatal.setText("Batal");
        jButtonBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBatalMouseClicked(evt);
            }
        });
        jButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalActionPerformed(evt);
            }
        });

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSimpanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDurasi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSinopsis, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPosterPath, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelGenre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelJudul, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldJudul)
                            .addComponent(jComboBoxGenre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerDurasi)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonBatal)
                                    .addComponent(jTextFieldPosterPath))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonBrowsePath)
                                    .addComponent(jButtonSimpan))))
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelSubJudulTambah)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelJudulTambah)
                        .addGap(259, 259, 259))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelJudulTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSubJudulTambah)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJudul))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGenre)
                    .addComponent(jComboBoxGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDurasi)
                    .addComponent(jSpinnerDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSinopsis)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPosterPath)
                    .addComponent(jTextFieldPosterPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowsePath))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBatal)
                    .addComponent(jButtonSimpan))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPosterPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPosterPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPosterPathActionPerformed

    private void jComboBoxGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGenreActionPerformed

    private void jButtonBrowsePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowsePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBrowsePathActionPerformed

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jButtonBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBatalMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonBatalMouseClicked

    private void jButtonSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimpanMouseClicked
        // TODO add your handling code here:
        try {
            String judul = jTextFieldJudul.getText();
            String genre = jComboBoxGenre.getSelectedItem().toString();
            int durasi = (int)jSpinnerDurasi.getValue();
            String sinopsis = jTextAreaSinopsis.getText().trim();
            String posterPath = jTextFieldPosterPath.getText().trim();

            if (judul.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Judul film tidak boleh kosong!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (durasi <= 0) {
                JOptionPane.showMessageDialog(this, "Durasi film harus lebih dari 0 menit!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Fungsi tambah data
            boolean sukses = controller.addFilm(judul, genre, durasi, sinopsis, posterPath);
            
            if (sukses) {
                JOptionPane.showMessageDialog(this, "Data film '" + judul + "' berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data ke database.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan input data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);        
        }
    }//GEN-LAST:event_jButtonSimpanMouseClicked

    private void jButtonBrowsePathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBrowsePathMouseClicked
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setDialogTitle("Pilih Gambar Poster Film");

        // Batasi file yang boleh dipilih hanya gambar
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Gambar (*.jpg, *.jpeg, *.png)", "jpg", "jpeg", "png");
        fileChooser.setFileFilter(filter);

        int hasilPilihan = fileChooser.showOpenDialog(this);

        if (hasilPilihan == JFileChooser.APPROVE_OPTION) {
            File fileTerpilih = fileChooser.getSelectedFile();

            String namaFilePoster = fileTerpilih.getName();

            jTextFieldPosterPath.setText(namaFilePoster);
        }
    }//GEN-LAST:event_jButtonBrowsePathMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogTambahFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogTambahFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogTambahFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogTambahFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogTambahFilm dialog = new DialogTambahFilm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonBrowsePath;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JComboBox<String> jComboBoxGenre;
    private javax.swing.JLabel jLabelDurasi;
    private javax.swing.JLabel jLabelGenre;
    private javax.swing.JLabel jLabelJudul;
    private javax.swing.JLabel jLabelJudulTambah;
    private javax.swing.JLabel jLabelPosterPath;
    private javax.swing.JLabel jLabelSinopsis;
    private javax.swing.JLabel jLabelSubJudulTambah;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerDurasi;
    private javax.swing.JTextArea jTextAreaSinopsis;
    private javax.swing.JTextField jTextFieldJudul;
    private javax.swing.JTextField jTextFieldPosterPath;
    // End of variables declaration//GEN-END:variables
}
