/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views.admin.FilmManagement;

import controllers.FilmController;
import models.Film;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import utils.ColorPalette;

/**
 *
 * @author Rafli Ahmad Fauzi
 */
public class DialogEditFilm extends javax.swing.JDialog {

    private final FilmController controller;
    private final int idFilm; // Menyimpan ID Film yang sedang diedit
    
    /**
     * Creates new form DialogEditFilm
     */
    public DialogEditFilm(java.awt.Frame parent, boolean modal, int idFilm) {
        super(parent, modal);
        initComponents();
        
        this.controller = new FilmController();
        this.idFilm = idFilm; 
        this.setLocationRelativeTo(parent);
        
        loadDataFilmLama();
        
        jPanel5.setBackground(ColorPalette.SIDEBAR);

        jButtonSimpanEdit.setBackground(ColorPalette.PRIMARY);
        jButtonSimpanEdit.setForeground(ColorPalette.WHITE);

        jButtonBatalEdit.setBackground(ColorPalette.BORDER);
        jButtonBatalEdit.setForeground(ColorPalette.SIDEBAR);

        jButtonBrowsePathEdit.setBackground(ColorPalette.SIDEBAR);
        jButtonBrowsePathEdit.setForeground(ColorPalette.WHITE);
    }
    
    private void loadDataFilmLama() {
        Film film = controller.getFilm(idFilm);
        
        if (film != null) {
            jTextFieldJudulEdit.setText(film.getJudul());
            jComboBoxGenreEdit.setSelectedItem(film.getGenre());
            jSpinnerDurasiEdit.setValue(film.getDurasiMenit());
            jTextAreaSinopsisEdit.setText(film.getSinopsis());
            jTextFieldPosterPathEdit.setText(film.getPosterPath());
        } else {
            JOptionPane.showMessageDialog(this, "Data film tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabelJudulEdit = new javax.swing.JLabel();
        jLabelSubJudulEdit = new javax.swing.JLabel();
        jLabelJudul3 = new javax.swing.JLabel();
        jTextFieldJudulEdit = new javax.swing.JTextField();
        jLabelGenre3 = new javax.swing.JLabel();
        jLabelDurasi3 = new javax.swing.JLabel();
        jLabelSinopsis3 = new javax.swing.JLabel();
        jLabelPosterPath3 = new javax.swing.JLabel();
        jTextFieldPosterPathEdit = new javax.swing.JTextField();
        jComboBoxGenreEdit = new javax.swing.JComboBox<>();
        jSpinnerDurasiEdit = new javax.swing.JSpinner();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaSinopsisEdit = new javax.swing.JTextArea();
        jButtonBrowsePathEdit = new javax.swing.JButton();
        jButtonBatalEdit = new javax.swing.JButton();
        jButtonSimpanEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Data Film");

        jPanel5.setBackground(new java.awt.Color(16, 25, 53));

        jLabelJudulEdit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelJudulEdit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJudulEdit.setText("Edit Film");

        jLabelSubJudulEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSubJudulEdit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubJudulEdit.setText("Edit Data Film dengan Mengubah Isi Field Dibawah");

        jLabelJudul3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJudul3.setText("Judul :");

        jLabelGenre3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenre3.setText("Genre :");

        jLabelDurasi3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDurasi3.setText("Durasi (Menit) :");

        jLabelSinopsis3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSinopsis3.setText("Sinopsis :");

        jLabelPosterPath3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPosterPath3.setText("Poster Path :");

        jTextFieldPosterPathEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPosterPathEditActionPerformed(evt);
            }
        });

        jComboBoxGenreEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Action", "Drama", "Horror", "Komedi", "Thriller", "Science Fiction", "Romantis" }));
        jComboBoxGenreEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGenreEditActionPerformed(evt);
            }
        });

        jSpinnerDurasiEdit.setModel(new javax.swing.SpinnerNumberModel());

        jTextAreaSinopsisEdit.setColumns(20);
        jTextAreaSinopsisEdit.setRows(5);
        jScrollPane4.setViewportView(jTextAreaSinopsisEdit);

        jButtonBrowsePathEdit.setText("Browse");
        jButtonBrowsePathEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBrowsePathEditMouseClicked(evt);
            }
        });
        jButtonBrowsePathEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowsePathEditActionPerformed(evt);
            }
        });

        jButtonBatalEdit.setText("Batal");
        jButtonBatalEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBatalEditMouseClicked(evt);
            }
        });
        jButtonBatalEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalEditActionPerformed(evt);
            }
        });

        jButtonSimpanEdit.setText("Simpan");
        jButtonSimpanEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSimpanEditMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDurasi3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSinopsis3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPosterPath3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelGenre3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelJudul3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldJudulEdit)
                            .addComponent(jComboBoxGenreEdit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerDurasiEdit)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonBatalEdit)
                                    .addComponent(jTextFieldPosterPathEdit))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonBrowsePathEdit)
                                    .addComponent(jButtonSimpanEdit))))
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelSubJudulEdit)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelJudulEdit)
                        .addGap(279, 279, 279))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelJudulEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSubJudulEdit)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldJudulEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJudul3))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGenre3)
                    .addComponent(jComboBoxGenreEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDurasi3)
                    .addComponent(jSpinnerDurasiEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSinopsis3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPosterPath3)
                    .addComponent(jTextFieldPosterPathEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowsePathEdit))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBatalEdit)
                    .addComponent(jButtonSimpanEdit))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPosterPathEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPosterPathEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPosterPathEditActionPerformed

    private void jComboBoxGenreEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGenreEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGenreEditActionPerformed

    private void jButtonBrowsePathEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBrowsePathEditMouseClicked
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setDialogTitle("Pilih Gambar Poster Film");

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Gambar (*.jpg, *.jpeg, *.png)", "jpg", "jpeg", "png");
        fileChooser.setFileFilter(filter);

        int hasilPilihan = fileChooser.showOpenDialog(this);

        if (hasilPilihan == JFileChooser.APPROVE_OPTION) {
            File fileTerpilih = fileChooser.getSelectedFile();
            jTextFieldPosterPathEdit.setText(fileTerpilih.getName());
        }
    }//GEN-LAST:event_jButtonBrowsePathEditMouseClicked

    private void jButtonBrowsePathEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowsePathEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBrowsePathEditActionPerformed

    private void jButtonBatalEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBatalEditMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonBatalEditMouseClicked

    private void jButtonBatalEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBatalEditActionPerformed

    private void jButtonSimpanEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimpanEditMouseClicked
        // TODO add your handling code here:
        try {
            String judul = jTextFieldJudulEdit.getText().trim();
            String genre = jComboBoxGenreEdit.getSelectedItem().toString();
            int durasi = (int)jSpinnerDurasiEdit.getValue();
            String sinopsis = jTextAreaSinopsisEdit.getText().trim();
            String posterPath = jTextFieldPosterPathEdit.getText().trim();

            if (judul.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Judul film tidak boleh kosong!", "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            boolean sukses = controller.editFilm(idFilm, judul, genre, durasi, sinopsis, posterPath);

            if (sukses) {
                JOptionPane.showMessageDialog(this, "Data film berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                this.dispose(); 
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui data ke database.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSimpanEditMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatalEdit;
    private javax.swing.JButton jButtonBrowsePathEdit;
    private javax.swing.JButton jButtonSimpanEdit;
    private javax.swing.JComboBox<String> jComboBoxGenreEdit;
    private javax.swing.JLabel jLabelDurasi3;
    private javax.swing.JLabel jLabelGenre3;
    private javax.swing.JLabel jLabelJudul3;
    private javax.swing.JLabel jLabelJudulEdit;
    private javax.swing.JLabel jLabelPosterPath3;
    private javax.swing.JLabel jLabelSinopsis3;
    private javax.swing.JLabel jLabelSubJudulEdit;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinnerDurasiEdit;
    private javax.swing.JTextArea jTextAreaSinopsisEdit;
    private javax.swing.JTextField jTextFieldJudulEdit;
    private javax.swing.JTextField jTextFieldPosterPathEdit;
    // End of variables declaration//GEN-END:variables
}
