/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jakoy;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author dzaky
 */
public class tampilDataPegawai extends javax.swing.JFrame {

    /**
     * Creates new form tampilDataPegawai
     */
    public tampilDataPegawai() {
        initComponents();
        tampilDataKasir();
    }
    
    public void tampilDataKasir() {
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Nama Lengkap", "Email", "Posisi"}, 0);
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_bioskop", "root", "");
            // Query sesuai nama kolom di database lu
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT id_user, nama, email, role FROM users WHERE role = 'Kasir'");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_user"), 
                    rs.getString("nama"), 
                    rs.getString("email"), 
                    rs.getString("role")
                });
            }
            tblPegawai.setModel(model); // Pastikan nama tabel lu tblPegawai
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal tampil data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPegawai = new javax.swing.JTable();
        btnTambahDataPegawai = new javax.swing.JButton();
        btnEditDataPegawai = new javax.swing.JButton();
        btnHapusDataPegawai = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnLihatDataPegawai = new javax.swing.JButton();
        sidebarpanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sidebarDashboard = new javax.swing.JLabel();
        sidebarFilm = new javax.swing.JLabel();
        sidebarStudio = new javax.swing.JLabel();
        sidebarCalendar = new javax.swing.JLabel();
        sidebarFnB = new javax.swing.JLabel();
        sidebarReport = new javax.swing.JLabel();
        sidebarLogout = new javax.swing.JLabel();
        sidebarReport1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 25, 53));
        jLabel1.setText("Data Pegawai");

        tblPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPegawai);

        btnTambahDataPegawai.setBackground(new java.awt.Color(204, 153, 0));
        btnTambahDataPegawai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambahDataPegawai.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahDataPegawai.setText("Tambah");
        btnTambahDataPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDataPegawaiActionPerformed(evt);
            }
        });

        btnEditDataPegawai.setBackground(new java.awt.Color(204, 153, 0));
        btnEditDataPegawai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditDataPegawai.setForeground(new java.awt.Color(255, 255, 255));
        btnEditDataPegawai.setText("Ubah");
        btnEditDataPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDataPegawaiActionPerformed(evt);
            }
        });

        btnHapusDataPegawai.setBackground(new java.awt.Color(204, 0, 0));
        btnHapusDataPegawai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapusDataPegawai.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusDataPegawai.setText("Hapus");
        btnHapusDataPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusDataPegawaiActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 153, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnLihatDataPegawai.setBackground(new java.awt.Color(204, 153, 0));
        btnLihatDataPegawai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLihatDataPegawai.setForeground(new java.awt.Color(255, 255, 255));
        btnLihatDataPegawai.setText("Lihat Detail Profil");
        btnLihatDataPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatDataPegawaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(434, 434, 434))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLihatDataPegawai)
                                .addGap(18, 18, 18)
                                .addComponent(btnTambahDataPegawai)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditDataPegawai)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapusDataPegawai)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahDataPegawai)
                    .addComponent(btnEditDataPegawai)
                    .addComponent(btnHapusDataPegawai)
                    .addComponent(jButton4)
                    .addComponent(btnLihatDataPegawai))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebarpanel.setBackground(new java.awt.Color(16, 25, 53));
        sidebarpanel.setPreferredSize(new java.awt.Dimension(240, 730));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/logo_bioskopin (180 x 116 piksel).png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(140, 76));

        sidebarDashboard.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        sidebarDashboard.setForeground(new java.awt.Color(239, 239, 239));
        sidebarDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        sidebarDashboard.setText("  Dashboard");

        sidebarFilm.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        sidebarFilm.setForeground(new java.awt.Color(239, 239, 239));
        sidebarFilm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/studio-1.png"))); // NOI18N
        sidebarFilm.setText("  Film");

        sidebarStudio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        sidebarStudio.setForeground(new java.awt.Color(239, 239, 239));
        sidebarStudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/studio.png"))); // NOI18N
        sidebarStudio.setText("  Studio");

        sidebarCalendar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        sidebarCalendar.setForeground(new java.awt.Color(239, 239, 239));
        sidebarCalendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/calendar.png"))); // NOI18N
        sidebarCalendar.setText("  Schedule");

        sidebarFnB.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        sidebarFnB.setForeground(new java.awt.Color(239, 239, 239));
        sidebarFnB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/food.png"))); // NOI18N
        sidebarFnB.setText("  F&B");

        sidebarReport.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        sidebarReport.setForeground(new java.awt.Color(204, 153, 0));
        sidebarReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/icons8-users-20 (1).png"))); // NOI18N
        sidebarReport.setText("   Employee");

        sidebarLogout.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        sidebarLogout.setForeground(new java.awt.Color(239, 239, 239));
        sidebarLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/logout.png"))); // NOI18N
        sidebarLogout.setText("  Logout");

        sidebarReport1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        sidebarReport1.setForeground(new java.awt.Color(239, 239, 239));
        sidebarReport1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/docs.png"))); // NOI18N
        sidebarReport1.setText("  Report");

        javax.swing.GroupLayout sidebarpanelLayout = new javax.swing.GroupLayout(sidebarpanel);
        sidebarpanel.setLayout(sidebarpanelLayout);
        sidebarpanelLayout.setHorizontalGroup(
            sidebarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarpanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(sidebarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidebarpanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(sidebarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sidebarDashboard)
                            .addComponent(sidebarFilm)
                            .addComponent(sidebarStudio)
                            .addComponent(sidebarFnB)
                            .addComponent(sidebarReport)
                            .addComponent(sidebarCalendar)
                            .addComponent(sidebarLogout)
                            .addComponent(sidebarReport1))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        sidebarpanelLayout.setVerticalGroup(
            sidebarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarpanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(sidebarDashboard)
                .addGap(18, 18, 18)
                .addComponent(sidebarFilm)
                .addGap(18, 18, 18)
                .addComponent(sidebarStudio)
                .addGap(18, 18, 18)
                .addComponent(sidebarCalendar)
                .addGap(18, 18, 18)
                .addComponent(sidebarFnB)
                .addGap(18, 18, 18)
                .addComponent(sidebarReport)
                .addGap(18, 18, 18)
                .addComponent(sidebarReport1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(sidebarLogout)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(sidebarpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditDataPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDataPegawaiActionPerformed
        // TODO add your handling code here:
        // Logic Tombol Ubah
        int i = tblPegawai.getSelectedRow();
        if(i == -1){
            JOptionPane.showMessageDialog(this, "Pilih baris data yang mau diubah dari tabel dulu!");
            return;
        }

        // 1. Ambil ID saja
        String id = tblPegawai.getValueAt(i, 0).toString();

        // 2. Lempar ID ke Constructor (Otomatis narik data dari DB)
        EditPegawai edit = new EditPegawai(id);
        edit.setVisible(true);

        // 3. Pasang "mata-mata"
        edit.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                tampilDataKasir();
            }
        });
    }//GEN-LAST:event_btnEditDataPegawaiActionPerformed

    private void btnLihatDataPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatDataPegawaiActionPerformed
        // TODO add your handling code here:
        // 1. Cek baris mana yang dipilih di tabel
        int row = tblPegawai.getSelectedRow();
        
        // Kalau bernilai -1, artinya user belum ngeklik baris apa pun
        if(row == -1){
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Pilih baris data pegawai di tabel terlebih dahulu!", 
                "Peringatan", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Hentikan proses biar gak error
        }

        // 2. Ambil ID dari baris yang dipilih (Kolom ID ada di index 0)
        String idUser = tblPegawai.getValueAt(row, 0).toString();

        // 3. Buka halaman ProfilePegawai dan kirim ID-nya
        ProfilePegawai profil = new ProfilePegawai(idUser);
        profil.setVisible(true);
    }//GEN-LAST:event_btnLihatDataPegawaiActionPerformed

    private void btnHapusDataPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusDataPegawaiActionPerformed
        // TODO add your handling code here:
        // Logic Tombol Hapus
        int row = tblPegawai.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris data yang mau dihapus dulu!");
            return;
        }
        String id = tblPegawai.getValueAt(row, 0).toString();
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin hapus ID " + id + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_bioskop", "root", "");
                PreparedStatement stmt = conn.prepareStatement("DELETE FROM users WHERE id_user = ?");
                stmt.setString(1, id);
                stmt.executeUpdate();

                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                tampilDataKasir(); // Refresh tabel
                conn.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal hapus: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusDataPegawaiActionPerformed

    private void btnTambahDataPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDataPegawaiActionPerformed
        // TODO add your handling code here:
        TambahPegawai addData = new TambahPegawai();
        addData.setVisible(true);

        // Pasang "mata-mata" biar pas jendela tambah ditutup, tabel langsung refresh
        addData.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                tampilDataKasir();
            }
        });
    }//GEN-LAST:event_btnTambahDataPegawaiActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilDataPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilDataPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilDataPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilDataPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilDataPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditDataPegawai;
    private javax.swing.JButton btnHapusDataPegawai;
    private javax.swing.JButton btnLihatDataPegawai;
    private javax.swing.JButton btnTambahDataPegawai;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sidebarCalendar;
    private javax.swing.JLabel sidebarDashboard;
    private javax.swing.JLabel sidebarFilm;
    private javax.swing.JLabel sidebarFnB;
    private javax.swing.JLabel sidebarLogout;
    private javax.swing.JLabel sidebarReport;
    private javax.swing.JLabel sidebarReport1;
    private javax.swing.JLabel sidebarStudio;
    private javax.swing.JPanel sidebarpanel;
    private javax.swing.JTable tblPegawai;
    // End of variables declaration//GEN-END:variables
}
