package views.admin;

import controllers.FnBController;
import models.FnBItem;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 * @author riikq
 */
public class FnBManagementPanel extends javax.swing.JPanel {
  private DefaultTableModel tableModel;
  private FnBController controller;

  /**
   * Creates new form FnBManagementPanel
   */
  public FnBManagementPanel() {
    // 1. Let NetBeans build the visual components first
    initComponents();

    // 2. Setup our MVC controller and table mapping
    this.controller = new FnBController();
    initTableConfiguration();

    // 3. Load records from MySQL
    refreshTableData();
  }

  private void initTableConfiguration() {
    tableModel = new DefaultTableModel(
        new Object[][] {},
        new String[] { "ID", "Nama FnB", "Kategori", "Harga", "Stok" }) {
      @Override
      public boolean isCellEditable(int row, int column) {
        return false;
      }
    };
    table.setModel(tableModel);
  }

  private void refreshTableData() {
    tableModel.setRowCount(0);
    ArrayList<FnBItem> items = controller.getAllItems();
    for (FnBItem item : items) {
      tableModel.addRow(new Object[] {
          item.getIdFnb(),
          item.getNamaFnb(),
          item.getKategori(),
          item.getHarga(),
          item.getStok()
      });
    }
  }

  private void clearForm() {
    txtNama.setText("");
    cbKategori.setSelectedIndex(0);
    txtHarga.setText("");
    txtStok.setText("");
    table.clearSelection();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    table = new javax.swing.JTable();
    jPanelForm = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    txtNama = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    cbKategori = new javax.swing.JComboBox<>();
    jLabel3 = new javax.swing.JLabel();
    txtHarga = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    txtStok = new javax.swing.JTextField();
    jPanelActions = new javax.swing.JPanel();
    btnCreate = new javax.swing.JButton();
    btnUpdate = new javax.swing.JButton();
    btnDelete = new javax.swing.JButton();
    btnClear = new javax.swing.JButton();

    table.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] {},
        new String[] {}));
    table.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tableMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(table);

    jPanelForm.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Item Kelola FnB"));

    jLabel1.setText("Nama FnB:");

    jLabel2.setText("Kategori:");

    cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Snack", "Minuman", "Berat" }));

    jLabel3.setText("Harga:");

    jLabel4.setText("Stok:");

    javax.swing.GroupLayout jPanelFormLayout = new javax.swing.GroupLayout(jPanelForm);
    jPanelForm.setLayout(jPanelFormLayout);
    jPanelFormLayout.setHorizontalGroup(
        jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNama))
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHarga))
                    .addGroup(jPanelFormLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStok)))
                .addContainerGap()));
    jPanelFormLayout.setVerticalGroup(
        jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    btnCreate.setText("Tambah (Create)");
    btnCreate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCreateActionPerformed(evt);
      }
    });
    jPanelActions.add(btnCreate);

    btnUpdate.setText("Ubah (Update)");
    btnUpdate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnUpdateActionPerformed(evt);
      }
    });
    jPanelActions.add(btnUpdate);

    btnDelete.setText("Hapus (Delete)");
    btnDelete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDeleteActionPerformed(evt);
      }
    });
    jPanelActions.add(btnDelete);

    btnClear.setText("Clear");
    btnClear.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnClearActionPerformed(evt);
      }
    });
    jPanelActions.add(btnClear);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(jPanelForm, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelActions, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap()));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelActions, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
  }// </editor-fold>//GEN-END:initComponents

  private void tableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tableMouseClicked
    int selectedRow = table.getSelectedRow();
    if (selectedRow != -1) {
      txtNama.setText(tableModel.getValueAt(selectedRow, 1).toString());
      cbKategori.setSelectedItem(tableModel.getValueAt(selectedRow, 2).toString());
      txtHarga.setText(tableModel.getValueAt(selectedRow, 3).toString());
      txtStok.setText(tableModel.getValueAt(selectedRow, 4).toString());
    }
  }// GEN-LAST:event_tableMouseClicked

  private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCreateActionPerformed
    String nama = txtNama.getText().trim();
    String kategori = cbKategori.getSelectedItem().toString();
    String hargaStr = txtHarga.getText().trim();
    String stokStr = txtStok.getText().trim();

    if (nama.isEmpty() || hargaStr.isEmpty() || stokStr.isEmpty()) {
      JOptionPane.showMessageDialog(this, "Semua input field wajib diisi!");
      return;
    }

    try {
      double harga = Double.parseDouble(hargaStr);
      int stok = Integer.parseInt(stokStr);

      if (controller.store(nama, kategori, harga, stok)) {
        JOptionPane.showMessageDialog(this, "Menu FnB baru berhasil ditambahkan!");
        refreshTableData();
        clearForm();
      } else {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data ke MySQL server.");
      }
    } catch (NumberFormatException e) {
      JOptionPane.showMessageDialog(this, "Format harga atau stok harus berupa angka valid!");
    }
  }// GEN-LAST:event_btnCreateActionPerformed

  private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateActionPerformed
    int selectedRow = table.getSelectedRow();
    if (selectedRow == -1) {
      JOptionPane.showMessageDialog(this, "Pilih baris pada tabel FnB yang ingin diubah terlebih dahulu!");
      return;
    }

    int id = (int) tableModel.getValueAt(selectedRow, 0);
    String nama = txtNama.getText().trim();
    String kategori = cbKategori.getSelectedItem().toString();
    String hargaStr = txtHarga.getText().trim();
    String stokStr = txtStok.getText().trim();

    try {
      double harga = Double.parseDouble(hargaStr);
      int stok = Integer.parseInt(stokStr);

      if (controller.update(id, nama, kategori, harga, stok)) {
        JOptionPane.showMessageDialog(this, "Data FnB berhasil diperbarui!");
        refreshTableData();
        clearForm();
      } else {
        JOptionPane.showMessageDialog(this, "Gagal mengubah data item.");
      }
    } catch (NumberFormatException e) {
      JOptionPane.showMessageDialog(this, "Validasi gagal! Periksa kembali nominal harga dan kuantitas stok.");
    }
  }// GEN-LAST:event_btnUpdateActionPerformed

  private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
    int selectedRow = table.getSelectedRow();
    if (selectedRow == -1) {
      JOptionPane.showMessageDialog(this, "Pilih baris menu FnB yang ingin dihapus!");
      return;
    }

    int id = (int) tableModel.getValueAt(selectedRow, 0);
    String nama = tableModel.getValueAt(selectedRow, 1).toString();

    int confirm = JOptionPane.showConfirmDialog(this,
        "Apakah Anda yakin menghapus '" + nama + "' dari menu bioskop?",
        "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
      if (controller.destroy(id)) {
        JOptionPane.showMessageDialog(this, "Item berhasil dihapus.");
        refreshTableData();
        clearForm();
      } else {
        JOptionPane.showMessageDialog(this, "Gagal menghapus item dari server database.");
      }
    }
  }// GEN-LAST:event_btnDeleteActionPerformed

  private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnClearActionPerformed
    clearForm();
  }// GEN-LAST:event_btnClearActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:initComponents
  private javax.swing.JButton btnClear;
  private javax.swing.JButton btnCreate;
  private javax.swing.JButton btnDelete;
  private javax.swing.JButton btnUpdate;
  private javax.swing.JComboBox<String> cbKategori;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanelActions;
  private javax.swing.JPanel jPanelForm;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable table;
  private javax.swing.JTextField txtHarga;
  private javax.swing.JTextField txtNama;
  private javax.swing.JTextField txtStok;
  // End of variables declaration//GEN-END:initComponents
}
