/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.kasir;

import java.awt.CardLayout;
import javax.swing.JPanel;
import models.BookingSession;

/**
 *
 * @author riikq
 */
public class MainBookingFramee extends javax.swing.JFrame {
    
    private BookingSession currentSession;
    private CardLayout cardLayout;
    private JPanel mainContainer;

    // The individual Wizard Panels
    private MovieSelectionPanel moviePanel;
    private ScheduleSelectionPanel schedulePanel;
    private SeatSelectionPanel seatPanel;
    private FnBPurchasePanel fnbPanel;
    private CheckoutTicketPanel checkoutPanel;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainBookingFramee.class.getName());

    /**
     * Creates new form MainBookingFramee
     */
    public MainBookingFramee() {
        initComponents();
        super("Bioskopin - Transaksi Kasir");

        // 1. Initialize Session and Layout
        currentSession = new BookingSession();
        cardLayout = new CardLayout();
        mainContainer = new JPanel(cardLayout);

        // 2. Instantiate the panels
        moviePanel = new MovieSelectionPanel(this);
        schedulePanel = new ScheduleSelectionPanel(this);
        seatPanel = new SeatSelectionPanel(this);
        fnbPanel = new FnBPurchasePanel(this);
        checkoutPanel = new CheckoutTicketPanel(this);

        // 3. Add panels to the CardLayout stack
        mainContainer.add(moviePanel, "MOVIE_PANEL");
        mainContainer.add(schedulePanel, "SCHEDULE_PANEL");
        mainContainer.add(seatPanel, "SEAT_PANEL");
        mainContainer.add(fnbPanel, "FNB_PANEL");
        mainContainer.add(checkoutPanel, "CHECKOUT_PANEL");

        // 4. Mount container to the window
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        this.setContentPane(mainContainer);
        this.setSize(900, 700);
        this.setLocationRelativeTo(null);
      }

      public BookingSession getSession() {
        return currentSession;
      }

      // --- NAVIGATION LOGIC ---
      public void goToMovieSelection() {
        cardLayout.show(mainContainer, "MOVIE_PANEL");
      }

      public void goToScheduleSelection() {
        cardLayout.show(mainContainer, "SCHEDULE_PANEL");
      }

      public void refreshSchedulePanel() {
        schedulePanel.loadSchedulesForSelectedMovie();
      }

      public void goToSeatSelection() {
        cardLayout.show(mainContainer, "SEAT_PANEL");
      }

      public void refreshSeatPanel(int capacity) {
        seatPanel.loadSeatGrid(capacity);
      }

      public void goToFnBSelection() {
        cardLayout.show(mainContainer, "FNB_PANEL");
        fnbPanel.refreshPanel();
      }

      public void goToCheckout() {
        cardLayout.show(mainContainer, "CHECKOUT_PANEL");
      }

      public void refreshCheckoutPanel() {
        checkoutPanel.generateReceipt();
      }

      public void restartTransaction() {
        currentSession.resetSession(); // Clear all data
        goToMovieSelection(); // Back to Step 1
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(318, 318, 318))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainBookingFramee().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
